### ISSUE TITLE
OrderStatisticTree.sol will not compile

### ISSUE THREAD

**Issue by mike80439** [drcode/ethereum-order-statistic-tree#2]
OrderStatisticTree.sol:157:22: Compiler error: Stack too deep.
        Node n=nodes[value];
                                 ^---^

**Comment by drcode** [comment]
Hi, I think this is a new regression in the solidity compiler... I will contact the ethdev team and we'll see what they say.

**Comment by drcode** [comment]
Actually, I'm guessing what's happening is that the compiler guys are starting to marshall some of the "stack registers" for alternate purposes, progressively lowering the number of stack spots available for local variables. I will see what they say, but unless they do the correct fix soon (offloading stack data into EVM memory, which I know is in their game plan) I will need to refactor the code a bit to lower the number of local variables- I probably won't have time for this though before early next week.

**Comment by mike80439** [comment]
Thanks.

**Comment by drcode** [comment]
FYI, chriseth posted a suggested fix here, I will update when I have time:

https://github.com/ethereum/cpp-ethereum/issues/1145#event-242130975

**Comment by drcode** [comment]
Now fixed.
